import { Teacher } from "./schema";

const demoTeachers: Teacher[] = [
	{
		phoneNumber: "",
		name: "teacher0",
		availability: [
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher1",
		availability: [
			[0, 4],
			[0, 5],
			[0, 6],
			[2, 4],
			[2, 5],
			[2, 6],
		],
		schedule: [
			[null, null, null, null, undefined, undefined, undefined],
			[null, null, null, null, null, null, null],
			[null, null, null, null, undefined, undefined, undefined],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher2",
		availability: [
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
		],
	},
	{
		phoneNumber: "",
		name: "teacher3",
		availability: [
			[2, 4],
			[2, 5],
			[2, 6],
			[4, 0],
			[4, 1],
			[4, 2],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[null, null, null, null, undefined, undefined, undefined],
			[null, null, null, null, null, null, null],
			[undefined, undefined, undefined, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher4",
		availability: [
			[0, 0],
			[0, 1],
			[1, 0],
			[1, 1],
			[2, 0],
			[2, 1],
			[3, 0],
			[3, 1],
			[4, 0],
			[4, 1],
		],
		schedule: [
			[undefined, undefined, null, null, null, null, null],
			[undefined, undefined, null, null, null, null, null],
			[undefined, undefined, null, null, null, null, null],
			[undefined, undefined, null, null, null, null, null],
			[undefined, undefined, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher5",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
		],
		schedule: [
			[undefined, undefined, undefined, undefined, undefined, null, null],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[undefined, undefined, undefined, undefined, undefined, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher6",
		availability: [
			[2, 0],
			[2, 1],
			[2, 2],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[undefined, undefined, undefined, null, null, null, null],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher7",
		availability: [
			[1, 0],
			[3, 0],
			[3, 1],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[undefined, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[undefined, undefined, null, null, null, null, null],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher8",
		availability: [
			[2, 5],
			[2, 6],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, undefined, undefined],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, undefined, undefined],
		],
	},
	{
		phoneNumber: "",
		name: "teacher9",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[1, 0],
			[1, 4],
			[1, 5],
			[1, 6],
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[3, 0],
			[3, 4],
			[3, 5],
			[3, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[undefined, null, null, null, undefined, undefined, undefined],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[undefined, null, null, null, undefined, undefined, undefined],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher10",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
		],
	},
	{
		phoneNumber: "",
		name: "teacher11",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher12",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
		],
	},
	{
		phoneNumber: "",
		name: "teacher13",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
		],
	},
	{
		phoneNumber: "",
		name: "teacher14",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher15",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
		],
	},
	{
		phoneNumber: "",
		name: "teacher16",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher17",
		availability: [
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
		],
	},
	{
		phoneNumber: "",
		name: "teacher18",
		availability: [
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
		],
	},
	{
		phoneNumber: "",
		name: "teacher19",
		availability: [
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
		],
	},
	{
		phoneNumber: "",
		name: "teacher20",
		availability: [
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[null, null, null, undefined, undefined, undefined, undefined],
			[null, null, null, null, null, null, null],
			[null, null, null, undefined, undefined, undefined, undefined],
		],
	},
	{
		phoneNumber: "",
		name: "teacher21",
		availability: [
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[undefined, undefined, undefined, undefined, undefined, null, null],
			[undefined, undefined, undefined, undefined, undefined, null, null],
			[undefined, undefined, undefined, undefined, undefined, null, null],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher22",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher23",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher24",
		availability: [
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher25",
		availability: [
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
		],
		schedule: [
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher26",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
		],
	},
	{
		phoneNumber: "",
		name: "teacher27",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[undefined, undefined, undefined, undefined, undefined, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[undefined, undefined, undefined, undefined, undefined, null, null],
		],
	},
	{
		phoneNumber: "",
		name: "teacher28",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[null, null, null, null, null, null, null],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
		],
	},
	{
		phoneNumber: "",
		name: "teacher29",
		availability: [
			[0, 0],
			[0, 1],
			[0, 2],
			[0, 3],
			[0, 4],
			[0, 5],
			[0, 6],
			[1, 0],
			[1, 1],
			[1, 2],
			[1, 3],
			[1, 4],
			[1, 5],
			[1, 6],
			[2, 0],
			[2, 1],
			[2, 2],
			[2, 3],
			[2, 4],
			[2, 5],
			[2, 6],
			[3, 0],
			[3, 1],
			[3, 2],
			[3, 3],
			[3, 4],
			[3, 5],
			[3, 6],
			[4, 0],
			[4, 1],
			[4, 2],
			[4, 3],
			[4, 4],
			[4, 5],
			[4, 6],
		],
		schedule: [
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
			[
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
				undefined,
			],
		],
	},
];
export default demoTeachers;
