import { Subject } from "./schema";


// subject: "++id,&name,gradeId", // periods, full Mark,  description, teacherIds
const DemoSubjects: Subject[] = [
	{ schoolId: "Demo", name: "Religion", periods: 2, gradeId: 0 },
	{ schoolId: "Demo", name: "Math", periods: 4, gradeId: 0 },
	{ schoolId: "Demo", name: "Biology", periods: 2, gradeId: 0 },
	{ schoolId: "Demo", name: "IT", periods: 2, gradeId: 0 },
	{ schoolId: "Demo", name: "French", periods: 3, gradeId: 0 },
	{ schoolId: "Demo", name: "chemistry and (physics in middle)", periods: 2, gradeId: 0 },
	{ schoolId: "Demo", name: "History Geography", periods: 3, gradeId: 0 },
	{ schoolId: "Demo", name: "Philosophy and Patriotism", periods: 1, gradeId: 0 },
	{ schoolId: "Demo", name: "French", periods: 2, gradeId: 0 },
	{ schoolId: "Demo", name: "English", periods: 5, gradeId: 0 },
	{ schoolId: "Demo", name: "Arts", periods: 1, gradeId: 0 },
	{ schoolId: "Demo", name: "PA", periods: 1, gradeId: 0 },
	{ schoolId: "Demo", name: "Music", periods: 1, gradeId: 0 },
	{ schoolId: "Demo", name: "Arabic", periods: 6, gradeId: 0 },
	{ schoolId: "Demo", name: "English", periods: 3, gradeId: 1 },
	{ schoolId: "Demo", name: "English", periods: 3, gradeId: 1 },
	{ schoolId: "Demo", name: "Religion", periods: 2, gradeId: 1 },
	{ schoolId: "Demo", name: "Biology", periods: 2, gradeId: 1 },
	{ schoolId: "Demo", name: "Math", periods: 4, gradeId: 1 },
	{ schoolId: "Demo", name: "IT", periods: 1, gradeId: 1 },
	{ schoolId: "Demo", name: "French", periods: 3, gradeId: 1 },
	{ schoolId: "Demo", name: "chemistry and (physics in middle)", periods: 2, gradeId: 1 },
	{ schoolId: "Demo", name: "History Geography", periods: 3, gradeId: 1 },
	{ schoolId: "Demo", name: "Philosophy and Patriotism", periods: 1, gradeId: 1 },
	{ schoolId: "Demo", name: "French", periods: 2, gradeId: 1 },
	{ schoolId: "Demo", name: "Arts", periods: 1, gradeId: 1 },
	{ schoolId: "Demo", name: "PA", periods: 1, gradeId: 1 },
	{ schoolId: "Demo", name: "Music", periods: 1, gradeId: 1 },
	{ schoolId: "Demo", name: "Arabic", periods: 6, gradeId: 1 },
	{ schoolId: "Demo", name: "French", periods: 3, gradeId: 2 },
	{ schoolId: "Demo", name: "History Geography", periods: 3, gradeId: 2 },
	{ schoolId: "Demo", name: "Religion", periods: 2, gradeId: 2 },
	{ schoolId: "Demo", name: "Biology", periods: 3, gradeId: 2 },
	{ schoolId: "Demo", name: "Math", periods: 6, gradeId: 2 },
	{ schoolId: "Demo", name: "English", periods: 4, gradeId: 2 },
	{ schoolId: "Demo", name: "Arabic", periods: 6, gradeId: 2 },
	{ schoolId: "Demo", name: "IT", periods: 1, gradeId: 2 },
	{ schoolId: "Demo", name: "chemistry and (physics in middle)", periods: 3, gradeId: 2 },
	{ schoolId: "Demo", name: "Philosophy and Patriotism", periods: 1, gradeId: 2 },
	{ schoolId: "Demo", name: "Arts", periods: 1, gradeId: 2 },
	{ schoolId: "Demo", name: "PA", periods: 1, gradeId: 2 },
	{ schoolId: "Demo", name: "Music", periods: 1, gradeId: 2 },
	{ schoolId: "Demo", name: "English", periods: 2, gradeId: 3 },
	{ schoolId: "Demo", name: "French", periods: 3, gradeId: 3 },
	{ schoolId: "Demo", name: "Physics", periods: 3, gradeId: 3 },
	{ schoolId: "Demo", name: "Religion", periods: 2, gradeId: 3 },
	{ schoolId: "Demo", name: "Math", periods: 6, gradeId: 3 },
	{ schoolId: "Demo", name: "Biology", periods: 3, gradeId: 3 },
	{ schoolId: "Demo", name: "English", periods: 3, gradeId: 3 },
	{ schoolId: "Demo", name: "IT", periods: 1, gradeId: 3 },
	{ schoolId: "Demo", name: "chemistry and (physics in middle)", periods: 2, gradeId: 3 },
	{ schoolId: "Demo", name: "History Geography", periods: 2, gradeId: 3 },
	{ schoolId: "Demo", name: "Philosophy and Patriotism", periods: 2, gradeId: 3 },
	{ schoolId: "Demo", name: "Arabic", periods: 4, gradeId: 3 },
	{ schoolId: "Demo", name: "Arts", periods: 1, gradeId: 3 },
	{ schoolId: "Demo", name: "PA", periods: 1, gradeId: 3 },
	{ schoolId: "Demo", name: "English", periods: 2, gradeId: 4 },
	{ schoolId: "Demo", name: "French", periods: 3, gradeId: 4 },
	{ schoolId: "Demo", name: "Physics", periods: 2, gradeId: 4 },
	{ schoolId: "Demo", name: "Biology", periods: 3, gradeId: 4 },
	{ schoolId: "Demo", name: "Religion", periods: 2, gradeId: 4 },
	{ schoolId: "Demo", name: "English", periods: 3, gradeId: 4 },
	{ schoolId: "Demo", name: "Arabic", periods: 4, gradeId: 4 },
	{ schoolId: "Demo", name: "Math", periods: 4, gradeId: 4 },
	{ schoolId: "Demo", name: "IT", periods: 1, gradeId: 4 },
	{ schoolId: "Demo", name: "chemistry and (physics in middle)", periods: 2, gradeId: 4 },
	{ schoolId: "Demo", name: "Physics", periods: 2, gradeId: 4 },
	{ schoolId: "Demo", name: "Math", periods: 3, gradeId: 4 },
	{ schoolId: "Demo", name: "Philosophy and Patriotism", periods: 2, gradeId: 4 },
	{ schoolId: "Demo", name: "Arts", periods: 1, gradeId: 4 },
	{ schoolId: "Demo", name: "PA", periods: 1, gradeId: 4 },
	{ schoolId: "Demo", name: "Arabic", periods: 4, gradeId: 4 },
	{ schoolId: "Demo", name: "French", periods: 3, gradeId: 5 },
	{ schoolId: "Demo", name: "Biology", periods: 4, gradeId: 5 },
	{ schoolId: "Demo", name: "Chemistry", periods: 3, gradeId: 5 },
	{ schoolId: "Demo", name: "Physics", periods: 3, gradeId: 5 },
	{ schoolId: "Demo", name: "English", periods: 4, gradeId: 5 },
	{ schoolId: "Demo", name: "Religion", periods: 1, gradeId: 5 },
	{ schoolId: "Demo", name: "Arabic", periods: 4, gradeId: 5 },
	{ schoolId: "Demo", name: "Math", periods: 5, gradeId: 5 },
	{ schoolId: "Demo", name: "Physics", periods: 2, gradeId: 5 },
	{ schoolId: "Demo", name: "Math", periods: 5, gradeId: 5 },
	{ schoolId: "Demo", name: "Philosophy and Patriotism", periods: 1, gradeId: 5 },
];

export default DemoSubjects;
